name: indexed_drag_target
description: "Drag and drop Widgets into lists and grids."
version: 0.0.1
homepage: https://www.github.com/andyhorn/indexed_drag_target

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
